version: "3.8"
services:
  app:
    build:
      context: ./
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    command: "uvicorn spotify.app:app --reload --host 0.0.0.0"
  backend:
    build:
      context: ./
    ports:
      - 8001:8000
